# Docker Compose Override
# Local development overrides for docker-compose.yml

version: '3.8'

services:
  homeboard:
    # Override for development - only enable when needed
    # volumes:
    #   # Mount source code for hot reload in development
    #   - .:/app:cached
    #   - go-mod-cache:/go/pkg/mod
    # environment:
    #   - GO_ENV=development
    #   - DEBUG=true
    # command: ["go", "run", "cmd/server/main.go", "-config", "/app/config.json", "-verbose"]
    
  # Development tools
  adminer:
    image: adminer:latest
    container_name: homeboard-adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres-dev
    networks:
      - homeboard-network
    profiles:
      - dev-tools

volumes:
  go-mod-cache:
    driver: local