# ADK Widget Builder Service Configuration

server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: adk-widget-builder
  
  # Jackson configuration for JSON processing
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# ADK Configuration
adk:
  app-name: widget_builder
  model: gemini-2.0-flash

# Google Cloud Configuration
google:
  cloud:
    project-id: ${GOOGLE_CLOUD_PROJECT_ID:}
    location: ${GOOGLE_CLOUD_LOCATION:us-central1}

# Vertex AI Configuration
vertex:
  ai:
    project-id: ${VERTEX_AI_PROJECT_ID:${google.cloud.project-id}}
    location: ${VERTEX_AI_LOCATION:${google.cloud.location}}

# Logging Configuration
logging:
  level:
    com.homeboard.adk: INFO
    com.google.adk: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# Session Management
session:
  cleanup:
    interval: 3600 # seconds (1 hour)
    max-age: 86400 # seconds (24 hours)